# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161011005748 on 2016-10-11 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0000000', max_length=20, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('tumor', models.CharField(blank=True, choices=[('S', 'Solid'), ('A', 'Ascites')], max_length=1, null=True)),
                ('anatomic_pathology', models.CharField(blank=True, max_length=60, null=True)),
                ('tumor_markers', models.CharField(blank=True, max_length=60, null=True)),
                ('site', models.CharField(blank=True, choices=[('S', 'Subcute'), ('I', 'IpSlice'), ('C', 'IpCells')], max_length=1, null=True)),
                ('position', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True)),
                ('treatment', models.CharField(blank=True, choices=[('N', 'No'), ('S', 'StartingDate'), ('T', 'Type'), ('D', 'Dose'), ('A', 'AdministratorRoute')], max_length=1, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('actual_state', models.CharField(blank=True, max_length=60, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('datins', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Node')),
            ],
        ),
    ]
